### ISSUE TITLE
1330nm FDTD data @Guruvaiah

### ISSUE THREAD

**Issue by Guruvaiah188** [raghu1153/MetaOptics#1]
[Phase, Transmission vs Radius of Cylinder at 1330nm.xlsx](https://github.com/raghu1153/MetaOptics/files/5257443/Phase.Transmission.vs.Radius.of.Cylinder.at.1330nm.xlsx)

**Comment by raghu1153** [comment]
Will be added to the FDTD data directory. Thanks.
